@startuml

class Asociacion {

}
class Conferencia {

}
class Evento {

}
class Localizacion {

}
class Miembro {

}
class MiembroJuntaDirectiva {

}
class Persona {

}
class ReunionJuntaDirectiva {

}
@enduml